AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create RDS instance'

Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: MyNewRDS
      MasterUsername: admin
      # Best Practice -> Use KMS (Key Management Service) or Secrets Manager to store the password
      MasterUserPassword: ''
      DBInstanceClass: 'db.t3.micro'
      Engine: mysql
      EngineVersion: '8.0.35'
      AllocatedStorage: 20
      BackupRetentionPeriod: 7
    DeletionPolicy: Delete # Avoid snapshot creation when deleting the RDS instance
